### ISSUE TITLE
Fix Minor Typos in README

### ISSUE THREAD

**Issue by c-nv-s** [davidscottmills/goeditorjs#1]
Thanks for this really useful code.
just a few typos in the example code in the readme
```
&goeditorjs.BlockParagraphHandler{},
&goeditorjs.BlockListHandler{},
&goeditorjs.BlockCodeBoxHandler{},
```

I believe should be:

```
&goeditorjs.ParagraphHandler{},
&goeditorjs.ListHandler{},
&goeditorjs.CodeBoxHandler{},
```

**Comment by davidscottmills** [comment]
Thanks for the feedback. This has been closed in [25aad9d25](https://github.com/davidscottmills/goeditorjs/commit/25aad9d254b494faf5eedcc0f384c57b3b938fb2).
